### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_1_lib_blockies___default.a is not a constructor

### ISSUE THREAD

**Issue by okwme** [eth-button/lib-blockies#1]
``` 16 | constructor(props) {
  17 | 
  18 |    console.log(Blockie)
> 19 |   const identicon = new Blockie(this.props.address);
  20 |   // const canvas = identicon.createCanvas(8);
  21 | 
````

**Comment by eth-button** [comment]
This issue is 18 days old and I'm just now seeing it!  I'm terribly sorry.  You've made me aware that I don't watch any of my own repositories, so I'll fix that right away.

I'll close this out when I have a fix.  What environment are you seeing this in?

**Comment by eth-button** [comment]
[3f0e5af2cb12cae2fb2eb216755a2a80684681e1](https://github.com/eth-button/lib-blockies/commit/3f0e5af2cb12cae2fb2eb216755a2a80684681e1) should fix this
